### ISSUE TITLE
Suggestion: For each wallet there should be a file: `[wallet-name]/index.ts`

### ISSUE THREAD

**Issue by kien-ngo** [fluidkey/walletbeat#15]
I might be jumping the gun here but eventually the array in `data.ts` will just get too large -> harder to maintain.

I think we can create a folder called `wallets`, then whenever a contributor wants to add a wallet, they can create an index file like this: `wallets/trust-wallet/index.ts`

Then all the wallet files will be exported to `wallets/index.ts` as:

```ts
// wallets/index.ts
import TrustWallet from "./trust-wallet";
import ZerionWallet from "./zerion-wallet";

export const allWallets = [TrustWallet, ZerionWallet, ...];
```

**Comment by mozrt2** [comment]
I thought the same :) The unique file system was a way to get started quickly but agree that it's becoming increasingly difficult to maintain as numbers grow - will add this to the to-do

**Comment by mozrt2** [comment]
Implemented this now - much better structure, thanks for suggesting!
