### ISSUE TITLE
Add link to the wallet's official repo

### ISSUE THREAD

**Issue by kien-ngo** [fluidkey/walletbeat#6]
Hey there, cool project you got here! I'll definitely put up some PRs.

Can we consider adding the column (on the UI) to show ~~whether a wallet is opensource and~~ the URL to its repo?

(edit: ok there is a label for "open source", I didn't see that lol)

**Comment by mozrt2** [comment]
Hey, great suggestion @kien-ngo - will add a link to each GitHub where the license type is. Looking forward to the PRs! :)

**Comment by kien-ngo** [comment]
Hi @mozrt2 I think for this issue we can add the git(hub/lab) organization page. Because there might be multiple repo for each platform:
- for mobile they might have 2 separate repo for android & ios
- for browser they might have diff repos for chromium, firefox (I saw one has an extension for the upcoming Arc browser too!)

So inititally, we can just add the organization page, for example: https://github.com/zeriontech

**Comment by mozrt2** [comment]
Yes, that makes sense @kien-ngo - I like the approach :) Thanks for all the contributions, really appreciate it!

**Comment by kien-ngo** [comment]
Ty ser I'll put up some PRs this weekend
